/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.veehait.devicecheck.appattest

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class ResourceUtilsTest : StringSpec({
    "readTextResource works and omits comments" {
        javaClass.readTextResource("/iOS14-assertion-response-base64.cbor") shouldBe
            "omlzaWduYXR1cmVYRzBFAiEA+LKWlfu0VR2yfqa8DFs+IaWvovmpCni3YgkI2RhtbLECICeLPi5bJCnmp5PVMBnR9fsrJJ" +
            "nlLLWUf2BTjQe4xcm7cWF1dGhlbnRpY2F0b3JEYXRhWCVFZRLqfiaUdquT4beXFoVZL/c/iUrA7C/VSAigi/tsj0AAAAAB"
    }
})
