/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package devicecheck.appattest

class Library {
    @Suppress("FunctionOnlyReturningConstant")
    fun someLibraryMethod(): Boolean {
        return true
    }
}
