name: CI Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1.0.3
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: ./gradlew build
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle.lockfile
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle.lockfile
          configuration-cache-exact: true
  codecov:
    name: Publish coverage to Codecov
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ./gradlew jacocoTestReport
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: jacocoTestReport
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle.lockfile
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle.lockfile
          configuration-cache-exact: true
      - name: Codecov
        uses: codecov/codecov-action@v1.4.1
        with:
          file: build/reports/jacoco/test/jacocoTestReport.xml
  artifacts:
    name: Upload artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ./gradlew jar javadocJar sourcesJar
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: jar javadocJar sourcesJar
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle.lockfile
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle.lockfile
          configuration-cache-exact: true
      - name: Upload JAR, Javadoc, and source artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: artifacts-jar-javadoc-sources
          path: build/libs/
          if-no-files-found: error
  publish:
    name: Publish Maven package
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ./gradlew publish
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: publish
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle.lockfile
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle.lockfile
          configuration-cache-exact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

