name: CI Build

on: [push, pull_request]

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1.0.3
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    name: Build & check JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-JDK-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-JDK-${{ matrix.java }}-gradle
      - name: ./gradlew assemble
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: assemble
      - name: ./gradlew check
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: check
  codecov:
    name: Publish coverage to Codecov
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-JDK-11-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-JDK-11-gradle
      - name: "./gradlew check"
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: check
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          file: build/reports/jacoco/test/jacocoTestReport.xml
  artifacts:
    name: Upload artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: "./gradlew jar javadocJar sourcesJar"
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: jar javadocJar sourcesJar
      - name: Upload JAR, Javadoc, and source artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: artifacts-jar-javadoc-sources
          path: build/libs/
          if-no-files-found: error
  publish:
    name: Publish Maven package
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: ./gradlew publish
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

